### ISSUE TITLE
'space-cli setup' does not clean up after encountering error-state

### ISSUE THREAD

**Issue by ledex** [spaceuptech/space-cli#6]
When the command `space-cli setup` encounters an error state while setting things up, the container `space-cloud-gateway`  and the network `space-cloud` might have already been created and are not removed. This behaviour leads to errors when trying to setup SpaceCloud in further iterations. Two encountered errors can be found below.

`ERRO[0000] Container (space-cloud-gateway) already exists  error=`

`ERRO[0000] Unable to start container (space-cloud-gateway)  error="Error response from daemon: network space-cloud is ambiguous (6 matches found on name)"`

**Comment by ledex** [comment]
A possible solution to this problem would be to run `docker network rm space-cloud` and `docker rm space-cloud-gateway `when encountering an error-state. The side-effects of this have to be checked first, however.

**Comment by YourTechBud** [comment]
@ledex yes this makes sense. As a hack, you can run `space-cli destroy` for now.

Can you raise the same issue in the Space Cloud repo? The space cli binary is in there. I'll archive this repo to avoid confusion.

**Comment by ledex** [comment]
Done, see #[1090 ](https://github.com/spaceuptech/space-cloud/issues/1090)
